const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '../../');
const TARGET_ROOT = 'C:\\Projects\\fais-payroll-srs';
const OUTPUT_JSON = path.join(PROJECT_ROOT, '.agents/architecture_map.json');
const OUTPUT_MD = 'C:\\Users\\ICTDO-James\\Documents\\Fais Project\\FAIS\\ARCHITECTURE.md';

function scanDirectory(dir, fileList = [], filterExt = []) {
    if (!fs.existsSync(dir)) return fileList;
    const files = fs.readdirSync(dir);
    
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            fileList = scanDirectory(fullPath, fileList, filterExt);
        } else {
            if (filterExt.length === 0 || filterExt.some(ext => file.endsWith(ext))) {
                fileList.push(fullPath);
            }
        }
    }
    return fileList;
}

function getRelativePath(fullPath) {
    return path.relative(TARGET_ROOT, fullPath).replace(/\\/g, '/');
}

function analyzeModels() {
    const modelsDir = path.join(TARGET_ROOT, 'app/Models');
    const files = scanDirectory(modelsDir, [], ['.php']);
    return files.map(file => {
        const content = fs.readFileSync(file, 'utf-8');
        const isPivot = content.includes('extends Pivot');
        return {
            path: getRelativePath(file),
            type: isPivot ? 'Pivot' : 'Model',
            name: path.basename(file, '.php')
        };
    });
}

function analyzeRoutes() {
    const routesDir = path.join(TARGET_ROOT, 'routes');
    const files = scanDirectory(routesDir, [], ['.php']);
    return files.map(file => {
        return {
            path: getRelativePath(file),
            type: 'RouteFile',
            name: path.basename(file)
        };
    });
}

function analyzeReactComponents() {
    const pagesDir = path.join(TARGET_ROOT, 'resources/js/Pages');
    const compDir = path.join(TARGET_ROOT, 'resources/js/Components');
    const files = [
        ...scanDirectory(pagesDir, [], ['.tsx', '.jsx']),
        ...scanDirectory(compDir, [], ['.tsx', '.jsx'])
    ];
    
    return files.map(file => {
        return {
            path: getRelativePath(file),
            type: file.includes('Pages') ? 'Page' : 'Component',
            name: path.basename(file)
        };
    });
}

function runScanner() {
    console.log("Scanning project architecture...");
    
    const architecture = {
        models: analyzeModels(),
        routes: analyzeRoutes(),
        react: analyzeReactComponents(),
        scanned_at: new Date().toISOString()
    };

    // Write JSON map
    if (!fs.existsSync(path.dirname(OUTPUT_JSON))) {
        fs.mkdirSync(path.dirname(OUTPUT_JSON), { recursive: true });
    }
    fs.writeFileSync(OUTPUT_JSON, JSON.stringify(architecture, null, 2));
    console.log(`Wrote JSON map to ${OUTPUT_JSON}`);

    // Generate Markdown for Obsidian Vault
    let mdContent = `# Project Architecture Map\n\n`;
    mdContent += `*Last updated: ${architecture.scanned_at}*\n\n`;
    mdContent += `This file is automatically generated by the Context Engine to serve as a backup context source for the AI.\n\n`;

    mdContent += `## Database Models\n`;
    architecture.models.forEach(m => {
        mdContent += `- **${m.name}** (\`${m.path}\`)\n`;
    });

    mdContent += `\n## Routes\n`;
    architecture.routes.forEach(r => {
        mdContent += `- **${r.name}** (\`${r.path}\`)\n`;
    });

    mdContent += `\n## React Components & Pages\n`;
    architecture.react.forEach(c => {
        mdContent += `- **${c.name}** (${c.type}) - \`${c.path}\`\n`;
    });

    // We will inject this into ARCHITECTURE.md
    if (fs.existsSync(OUTPUT_MD)) {
        let existingContent = fs.readFileSync(OUTPUT_MD, 'utf-8');
        // Look for the GSD architecture tags
        const startTag = '<!-- GSD:architecture-start source:ARCHITECTURE.md -->';
        const endTag = '<!-- GSD:architecture-end -->';
        
        if (existingContent.includes(startTag) && existingContent.includes(endTag)) {
            const regex = new RegExp(`${startTag}[\\s\\S]*?${endTag}`, 'm');
            existingContent = existingContent.replace(regex, `${startTag}\n\n${mdContent}\n${endTag}`);
            fs.writeFileSync(OUTPUT_MD, existingContent);
        } else {
            // Append if tags not found
            fs.appendFileSync(OUTPUT_MD, `\n\n${mdContent}`);
        }
    } else {
        fs.writeFileSync(OUTPUT_MD, mdContent);
    }
    
    console.log(`Updated Obsidian Vault at ${OUTPUT_MD}`);
}

runScanner();
